addons:
    apt:
        packages:
            - expect-dev  # provides unbuffer utility

language: python

python:
    - "2.7"

virtualenv:
    system_site_packages: true

env:
    global:
        - TESTS="0" LINT_CHECK="0" DOCS="0" VERSION="0.1.0" RELEASE="0.1.0" PROJECT="Python CFSSL" BRANCH_PROD="master" BRANCH_DOC="gh-pages"
    matrix:
        - TESTS="1"
        - DOCS="1"

install:
    - git clone --depth=1 https://github.com/LasLabs/python-quality-tools.git ${HOME}/python-quality-tools
    - export PATH=${HOME}/python-quality-tools/travis:${PATH}
    - travis_install

script:
    - travis_run

after_success:
    - travis_after_success
